### ISSUE TITLE
Device MSG100 Not Supported

### ISSUE THREAD

**Issue by Kung-Foo-Kamel** [bwp91/homebridge-meross-cloud#159]
**MSG100 is Not Supported.**

**Can you please support the MSG100**

**Using this item directly in Homekit is not really an option, its best supported under Homekit for more flexability**

** **

**Comment by Kung-Foo-Kamel** [comment]
For anyone finding this, I'm way to impatient so I found a solution, as I have seen this has been raised and closed many times by others.

You are best to install the other Meross app as that fully supports this device, then remove the native supported device from Homekit and have Homebridge add it instead, by doing this, you can have anything you like open and close your Garage Door, thus circumventing Apples stupid imposed rules on Garage Door openers.

I have a dummy switch setup and the Alexa plugin as well, so Alexa can fully operate the Garage Door as well, as this was another flaw, this device is supported by Alexa....as long as you live in the US, Amazon deem people in other locations not worthy of Garage Door control, also the US setup is also nerfed by having to use a stupid pin code, so once again, remove the Meross Alexa skill and add the dummy switch to Alexa instead.

I set up 4 automations in Homekit

1: When the dummy switch is toggled on, then open the Garage Door
2: When the dummy switch is toggled off, then close the Garage Door
3: When the Garage Door opens, then toggle dummy switch to on
4: When the Garage Door closes, then toggle dummy switch to off

This makes the garage door state synced between all three ecosystems (Alexa, Homebridge and Homekit) and allows you to do what ever the hell you want with the equipment you own, f you Apple and double f you Amazon.

**Comment by bwp91** [comment]
MSG100 is supported in the beta version of homebridge-meross, you’ll need to switch plugins
